CREATE TABLE `t_enterprise` (
  `id` bigint unsigned auto_increment NOT NULL,
  `app_id` varchar(64) NOT NULL DEFAULT '' COMMENT '企业id',
  `uid` varchar(64) NOT NULL DEFAULT '' COMMENT '所属用户id',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '企业名',
  `registration_number` char(18) NOT NULL DEFAULT '' COMMENT '统一社会信用代码（18位数字和字母）（唯一）',
  `district` varchar(128) NOT NULL DEFAULT '' COMMENT '行政区code硬编码',
  `legal_representative` varchar(50) NOT NULL DEFAULT '' COMMENT '法人',
  `register_capital` int unsigned NOT NULL DEFAULT '0' COMMENT '注册资本,万元',
  `registration_address` varchar(128) NOT NULL DEFAULT '' COMMENT '注册地址',
  `company_type` int unsigned NOT NULL DEFAULT '0' COMMENT '企业类型, 0未分类',
  `industry` varchar(10) NOT NULL DEFAULT '' COMMENT '行业代码',
  `legal_person_id_img` text NOT NULL COMMENT '法人身份证照片',
  `business_scope` text NOT NULL COMMENT '经营范围',
  `introduction` text NOT NULL COMMENT '企业介绍',
  `license_img` text NOT NULL COMMENT '营业执照照片',
  `estimate_value` int NOT NULL DEFAULT 0 COMMENT '估值，万元',
  `stage` int NOT NULL DEFAULT 0 COMMENT '融资阶段',
  `share_holder` varchar(128) NOT NULL DEFAULT '' COMMENT '股东',
  `share_holder_proportion` varchar(128) NOT NULL DEFAULT '' COMMENT '股东占比',
  `parent_id` varchar(64) DEFAULT '' COMMENT '所属机构id',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `app_id` (`app_id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `society_code` (`registration_number`),
  KEY `idx_register_capital` (`register_capital`),
  KEY  `idx_estimate_value` (`estimate_value`),
  KEY `idx_industry` (`industry`),
  KEY `district` (`district`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT '企业表';