CREATE TABLE `t_group` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `app_id` varchar(64) NOT NULL DEFAULT '' COMMENT '机构id',
  `uid` varchar(64) NOT NULL DEFAULT '' COMMENT '所属用户id',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '机构名',
  `registration_number` char(18) NOT NULL DEFAULT '' COMMENT '统一社会信用代码（18位数字和字母）（唯一）',
  `district` varchar(128) NOT NULL DEFAULT '' COMMENT '行政区code硬编码',
  `legal_representative` varchar(50) NOT NULL DEFAULT '' COMMENT '法人',
  `register_capital` int unsigned NOT NULL DEFAULT '0' COMMENT '注册资本,万元',
  `registration_address` varchar(128) NOT NULL DEFAULT '' COMMENT '注册地址',
  `company_type` int unsigned NOT NULL DEFAULT '0' COMMENT '机构类型, 0未分类',
  `industry` varchar(10) NOT NULL DEFAULT '' COMMENT '行业代码',
  `legal_representative_id_img` text COMMENT '法人照片',
  `business_scope` text NOT NULL COMMENT '经营范围',
  `introduction` text NOT NULL COMMENT '机构介绍',
  `license_img` text NOT NULL COMMENT '营业执照照片',
  `estimate_value` int NOT NULL DEFAULT '0' COMMENT '估值，万元',
  `invest_stage` int NOT NULL DEFAULT '0' COMMENT '投资阶段偏好',
  `invest_scope` int NOT NULL DEFAULT '0' COMMENT '投资领域',
  `share_holder_info` varchar(1024) NOT NULL DEFAULT '[]' COMMENT '股东信息',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `state` tinyint DEFAULT '0' COMMENT '状态 0-未审核 1-审核中 2-审核成功 3-审核失败',
  PRIMARY KEY (`id`),
  UNIQUE KEY `app_id` (`app_id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `registration_number` (`registration_number`),
  KEY `idx_register_capital` (`register_capital`),
  KEY `idx_estimate_value` (`estimate_value`),
  KEY `idx_industry` (`industry`),
  KEY `district` (`district`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb3 COMMENT='机构表'