// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audit": {
            "post": {
                "description": "审核提交",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "审核"
                ],
                "summary": "审核提交",
                "parameters": [
                    {
                        "description": "字段注解",
                        "name": "xxx",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/audit.Create"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/enterprise": {
            "post": {
                "description": "企业新建",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "企业"
                ],
                "summary": "企业新建",
                "parameters": [
                    {
                        "description": "字段注解",
                        "name": "xxx",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.Create"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/enterprise/search": {
            "post": {
                "description": "审核提交",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "审核"
                ],
                "summary": "审核提交",
                "parameters": [
                    {
                        "description": "字段注解",
                        "name": "xxx",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.Search"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Search"
                        }
                    }
                }
            }
        },
        "/valuate/search": {
            "get": {
                "description": "估值搜索",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "估值"
                ],
                "summary": "估值搜索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "企业ID",
                        "name": "appID",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Valuate"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "audit.Create": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "app_type": {
                    "description": "0-企业  1-机构",
                    "type": "integer"
                },
                "form_data": {
                    "description": "审核表单信息 json",
                    "type": "string"
                }
            }
        },
        "model.Enterprise": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "business_scope": {
                    "type": "string"
                },
                "company_type": {
                    "type": "integer"
                },
                "created_at": {
                    "description": "返回给业务侧",
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "estimate_value": {
                    "type": "integer"
                },
                "industry": {
                    "type": "string"
                },
                "introduction": {
                    "type": "string"
                },
                "label_district": {
                    "type": "string"
                },
                "label_industry": {
                    "type": "string"
                },
                "legal_representative": {
                    "type": "string"
                },
                "legal_representative_id_img": {
                    "type": "string"
                },
                "license_img": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "register_capital": {
                    "type": "integer"
                },
                "registration_address": {
                    "type": "string"
                },
                "registration_number": {
                    "type": "string"
                },
                "shar_holders_json": {
                    "type": "string"
                },
                "share_holder_info": {
                    "type": "string"
                },
                "stage": {
                    "type": "integer"
                },
                "state": {
                    "description": "审核状态",
                    "type": "integer"
                },
                "udated_at": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "model.EnterpriseMuttable": {
            "type": "object",
            "properties": {
                "business_scope": {
                    "type": "string"
                },
                "company_type": {
                    "type": "integer"
                },
                "district": {
                    "type": "string"
                },
                "estimate_value": {
                    "type": "integer"
                },
                "industry": {
                    "type": "string"
                },
                "introduction": {
                    "type": "string"
                },
                "legal_representative": {
                    "type": "string"
                },
                "legal_representative_id_img": {
                    "type": "string"
                },
                "license_img": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "register_capital": {
                    "type": "integer"
                },
                "registration_address": {
                    "type": "string"
                },
                "registration_number": {
                    "type": "string"
                },
                "shar_holders_json": {
                    "type": "string"
                },
                "share_holder_info": {
                    "type": "string"
                },
                "stage": {
                    "type": "integer"
                }
            }
        },
        "model.Valuate": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "created_at": {
                    "description": "返回给业务侧",
                    "type": "string"
                },
                "form_data": {
                    "type": "string"
                },
                "requested_at": {
                    "type": "string"
                },
                "state": {
                    "type": "integer"
                },
                "udated_at": {
                    "type": "string"
                },
                "valuate_id": {
                    "type": "string"
                }
            }
        },
        "request.Create": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "字段",
                    "$ref": "#/definitions/model.EnterpriseMuttable"
                },
                "parent_id": {
                    "description": "机构id 非必填",
                    "type": "string"
                },
                "uid": {
                    "description": "用户id",
                    "type": "string"
                }
            }
        },
        "request.RangeFilter": {
            "type": "object",
            "properties": {
                "gte": {
                    "description": "\u003e=",
                    "type": "integer"
                },
                "lte": {
                    "description": "\u003c=",
                    "type": "integer"
                },
                "type": {
                    "description": "0-注册资本 1-估值",
                    "type": "integer"
                }
            }
        },
        "request.Search": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "分页大小",
                    "type": "integer"
                },
                "range_filters": {
                    "description": "范围搜索",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.RangeFilter"
                    }
                },
                "sort": {
                    "description": "排序",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.Sort"
                    }
                },
                "text_filters": {
                    "description": "全文搜索",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.TextFilter"
                    }
                }
            }
        },
        "request.Sort": {
            "type": "object",
            "properties": {
                "column": {
                    "description": "0-注册资本 1-估值结果 2-名字",
                    "type": "integer"
                },
                "type": {
                    "description": "0-asc 1-desc",
                    "type": "integer"
                }
            }
        },
        "request.TextFilter": {
            "type": "object",
            "properties": {
                "type": {
                    "description": "0-行业代码",
                    "type": "integer"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "response.Search": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Enterprise"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
